name: Run tests

on:
  push:
    branches:
      - main
  pull_request: 
    branches: 
      - main

jobs:
  test-runner:
    name: test runner
    strategy: 
      matrix: 
        version: [18.18, 20.18]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.version }}
      - name: initialize deps
        run: npm install
      - name: run tests
        run: npm run test
